version: "3.9"
services:
  db:
    image: redis
  orchestra:
    build: .
    image: registry.anthonyoteri.com/docker-xen-orchestra
    ports:
      - "8443:443"
    volumes:
      - config:/config
    links:
     - db
    environment:
      - REDIS_URI=redis://db:6379/0
volumes:
  config: {}