version: "3.9"
services:
  db:
    image: redis:6.2.6
    command: ["redis-server", "--save", "60 ", "1"]
    volumes:
      - redis:/data
  orchestra:
    build: .
    image: registry.anthonyoteri.com/xen-orchestra:latest
    ports:
      - "8443:443"
    volumes:
      - config:/config
    links:
     - db
    environment:
      - REDIS_URI=redis://db:6379/0
volumes:
  config: {}
  redis: {}